
### All Contacts
GET http://localhost:8080/contacts

### Single Contact
GET http://localhost:8080/contacts/681c226099f0016aefefa6dc


GET https://cse341-spring2025-rz1w.onrender.com/contacts
GET https://cse341-spring2025-rz1w.onrender.com/contacts/681c226099f0016aefefa6dc
